export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const UPDATE_ITEM_PRICE = 'UPDATE_ITEM_PRICE';
// SET_PRODUCTS
 